FROM ruby:2.6

LABEL "com.github.actions.name"="Run tailor"
LABEL "com.github.actions.description"="Run tailor."
LABEL "com.github.actions.icon"="circle"
LABEL "com.github.actions.color"="red"

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
